<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductsTableSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('products')->insert([
            [
                'id' => 1,
                'title_ru' => 'Мешки полипропиленовые',
                'title_en' => 'Polypropylene Bags',
                'title_tm' => 'Polipropilen Torbalar',
                'description_ru' => '<p>Ширина от 35 см &ndash; 80 см<br>Плотность от 45 гр/м2<br>Цвет &ndash; белый, с возможностью добавления полос разных цветов<br>Грузоподъёмность &ndash; от 25 кг</p>\r\n<p>Горловина &ndash; термообрез<br>Дно &ndash; двойной подгиб, одинарная строчка</p>\r\n<p>Головина &ndash; подвернута и прошита<br>Дно &ndash; двойной подгиб, одинарная строчка</p>',
                'description_en' => '<p>Width: from 35 cm to 80 cm<br>Density: from 45 g/m&sup2;<br>Color: white, with the possibility of adding stripes in different colors<br>Load capacity: from 25 kg</p>\r\n<p><strong>Top</strong>: thermal cut<br><strong>Bottom</strong>: double fold, single stitch</p>\r\n<p><strong>Top</strong>: folded and stitched<br><strong>Bottom</strong>: double fold, single stitch</p>',
                'description_tm' => '<p>Ini: 35 sm-den 80 sm-a &ccedil;enli<br>Dykyzlygy: 45 gr/m&sup2;-den<br>Reňki: ak, d&uuml;rli reňkli zolaklaryň goşulmagy m&uuml;mkin<br>&Yacute;&uuml;k g&ouml;terijiligi: 25 kg-dan başla&yacute;ar</p>\r\n<p><strong>Agyz b&ouml;legi</strong>: &yacute;ylylyk bilen kesilen<br><strong>T&uuml;&yacute;d&uuml;k</strong>: iki gezek eplenilen, bir saply tikiş</p>\r\n<p><strong>Agyz b&ouml;legi</strong>: eplenilen we tikilen<br><strong>T&uuml;&yacute;k</strong>: iki gezek eplenilen, bir saply tikiш</p>',
                'is_active' => 1,
                'img' => 'img/p1.jpg',
                'ordering' => 0,
                'created_at' => '2024-12-27 04:48:10',
                'updated_at' => '2024-12-27 08:40:04',
            ],
            [
                'id' => 2,
                'title_ru' => 'Мешок полипропиленовый с полиэтиленовым вкладышем',
                'title_en' => 'Polypropylene Bag with Polyethylene Liner',
                'title_tm' => 'Polietilen Ýelmenili Polipropilen Torba',
                'description_ru' => '<p>Ширина от 35 см &ndash; 80 см<br>Плотность от 45 гр/м2<br>Вкладыш из ПНД, вшит в горловину мешка<br>Грузоподъёмность &ndash; от 25 кг</p>',
                'description_en' => '<p>Width: from 35 cm to 80 cm &nbsp;<br>Density: from 45 g/m&sup2; &nbsp;<br>Liner: HDPE, sewn into the bag&rsquo;s opening &nbsp;<br>Load capacity: from 25 kg &nbsp;</p>',
                'description_tm' => '<p>Ini: 35 sm-den 80 sm-a &ccedil;enli &nbsp;<br>Dykyzlygy: 45 gr/m&sup2;-den &nbsp;<br>&Yacute;elmen: HDPE, torbanyň agzyna tikilen &nbsp;<br>&Yacute;&uuml;k g&ouml;terijiligi: 25 kg-dan başla&yacute;ar&nbsp;</p>',
                'is_active' => 1,
                'img' => 'img/p2.jpg',
                'ordering' => 0,
                'created_at' => '2024-12-27 05:48:47',
                'updated_at' => '2024-12-27 05:48:47',
            ],
            [
                'id' => 3,
                'title_ru' => 'Полипропиленовый рукав',
                'title_en' => 'Polypropylene Sleeve',
                'title_tm' => 'Polipropilen Rukaw',
                'description_ru' => '<p>Ширина от 35 см &ndash; 80 см &nbsp;<br>Плотность от 45 гр/м2 &nbsp;<br>Цвет &ndash; белый, с возможностью добавления полос разных цветов</p>',
                'description_en' => '<p>Width: from 35 cm to 80 cm &nbsp;<br>Density: from 45 g/m&sup2; &nbsp;<br>Color: white, with the possibility of adding stripes in different colors</p>',
                'description_tm' => '<p>Ini: 35 sm-den 80 sm-a &ccedil;enli &nbsp;<br>Dykyzlygy: 45 gr/m&sup2;-den &nbsp;<br>Reňki: ak, d&uuml;rli reňkli zolaklaryň goşulmagy m&uuml;mkin</p>',
                'is_active' => 1,
                'img' => 'img/p3.jpg',
                'ordering' => 0,
                'created_at' => '2024-12-27 05:52:13',
                'updated_at' => '2024-12-27 05:52:13',
            ],
            [
                'id' => 4,
                'title_ru' => 'Полипропиленовый рукав для МКР',
                'title_en' => 'Polypropylene Sleeve for Big Bags (FIBC)',
                'title_tm' => 'MKR üçin Polipropilen Rukaw',
                'description_ru' => '<p>Фальцованный &nbsp;<br>Ширина от 80 см &ndash; 150 см &nbsp;<br>Плотность до 200 гр/м2 &nbsp;<br>УФ &ndash; от 1% &ndash; 2%&nbsp;</p>',
                'description_en' => '<p>Folded (gusseted) &nbsp;<br>Width: from 80 cm to 150 cm &nbsp;<br>Density: up to 200 g/m&sup2; &nbsp;<br>UV protection: from 1% to 2% &nbsp;</p>',
                'description_tm' => '<p>Faltsly (gatlanma g&ouml;rn&uuml;şli) &nbsp;<br>Ini: 80 sm-den 150 sm-a &ccedil;enli &nbsp;<br>Dykyzlygy: 200 gr/m&sup2; &ccedil;enli &nbsp;<br>UV goragy: 1%-den 2%-e &ccedil;enli&nbsp;</p>',
                'is_active' => 1,
                'img' => 'img/p4.jpg',
                'ordering' => 0,
                'created_at' => '2024-12-27 05:57:47',
                'updated_at' => '2024-12-27 08:41:33',
            ],
            [
                'id' => 5,
                'title_ru' => 'Полипропиленовое полотно',
                'title_en' => 'Polypropylene Fabric',
                'title_tm' => 'Polipropilen Matasy',
                'description_ru' => '<p>Ширина до 130 см &nbsp;<br>Плотность до 200 гр/м2 &nbsp;<br>УФ &ndash; от 1% &ndash; 2% &nbsp;<br>Ультразвуковая резка &ndash; сбоку, посередине</p>',
                'description_en' => '<p>Polypropylene Fabric &nbsp;<br>Width: up to 130 cm &nbsp;<br>Density: up to 200 g/m&sup2; &nbsp;<br>UV protection: from 1% to 2% &nbsp;<br>Ultrasonic cutting: at the side, in the middle</p>',
                'description_tm' => '<p>Ini: 130 sm-e &ccedil;enli &nbsp;<br>Dykyzlygy: 200 gr/m&sup2; &ccedil;enli &nbsp;<br>UV goragy: 1%-den 2%-e &ccedil;enli &nbsp;<br>Ultrases bilen kesmek: gapdalyndan &yacute;a-da ortasyndan</p>',
                'is_active' => 1,
                'img' => 'img/p5.jpg',
                'ordering' => 0,
                'created_at' => '2024-12-27 06:02:41',
                'updated_at' => '2024-12-27 06:02:41',
            ],
            [
                'id' => 6,
                'title_ru' => 'МКР (Биг Бэг)',
                'title_en' => 'Big Bag (FIBC)',
                'title_tm' => 'MKR (Uly Torba)',
                'description_ru' => '<p>4 стропный &ndash; 30 см &nbsp;<br>Ширина &ndash; от 75 см &nbsp;<br>Плотность до 200 гр/м2 &nbsp;<br>УФ &ndash; 1,5% &nbsp;<br>Грузоподъёмность &ndash; от 1000 кг</p>\r\n<p>Верх &ndash; открытый&nbsp;<br>Низ &ndash; глухой</p>\r\n<p>&nbsp;</p>',
                'description_en' => '<p>4 loops &ndash; 30 cm &nbsp;<br>Width: from 75 cm &nbsp;<br>Density: up to 200 g/m&sup2; &nbsp;<br>UV protection: 1.5% &nbsp;<br>Load capacity: from 1000 kg&nbsp;</p>\r\n<p>Top &ndash; open &nbsp;<br>Bottom &ndash; closed</p>',
                'description_tm' => '<p>4 a&yacute;lawly &ndash; 30 sm &nbsp;<br>Ini: 75 sm-den başla&yacute;ar &nbsp;<br>Dykyzlygy: 200 gr/m&sup2; &ccedil;enli &nbsp;<br>UV goragy: 1,5% &nbsp;<br>&Yacute;&uuml;k g&ouml;terijiligi: 1000 kg-dan başla&yacute;ar &nbsp;</p>\r\n<p>&Yacute;okary &ndash; a&ccedil;yk<br>Aşagy &ndash; &yacute;apyk</p>',
                'is_active' => 1,
                'img' => 'img/p6.jpg',
                'ordering' => 0,
                'created_at' => '2024-12-27 06:09:02',
                'updated_at' => '2024-12-27 06:09:02',
            ],
            [
                'id' => 7,
                'title_ru' => 'МКР (Биг Бэг)',
                'title_en' => 'Big Bag (FIBC)',
                'title_tm' => 'MKR (Uly Torba)',
                'description_ru' => '<p>4 стропный &ndash; 30 см &nbsp;<br>Ширина &ndash; от 75 см &nbsp;<br>Плотность до 200 гр/м2 &nbsp;<br>УФ &ndash; 1,5% &nbsp;<br>Грузоподъёмность &ndash; от 1000 кг &nbsp;</p>\r\n<p>Верх &ndash; люк<br>Низ &ndash; люк</p>',
                'description_en' => '<p>4 loops &ndash; 30 cm &nbsp;<br>Width: from 75 cm &nbsp;<br>Density: up to 200 g/m&sup2; &nbsp;<br>UV protection: 1.5% &nbsp;<br>Load capacity: from 1000 kg &nbsp;</p>\r\n<p>Top &ndash; filling spout &nbsp;<br>Bottom &ndash; discharging spout &nbsp;</p>',
                'description_tm' => '<p>4 a&yacute;lawly &ndash; 30 sm &nbsp;<br>Ini: 75 sm-den başla&yacute;ar &nbsp;<br>Dykyzlygy: 200 gr/m&sup2; &ccedil;enli &nbsp;<br>UV goragy: 1,5% &nbsp;<br>&Yacute;&uuml;k g&ouml;terijiligi: 1000 kg-dan başla&yacute;ar &nbsp;</p>\r\n<p>&Yacute;okary &ndash; agyz<br>Aşagy &ndash; agyz&nbsp;</p>',
                'is_active' => 1,
                'img' => 'img/p7.jpg',
                'ordering' => 0,
                'created_at' => '2024-12-27 06:13:15',
                'updated_at' => '2024-12-27 06:13:15',
            ],
            [
                'id' => 8,
                'title_ru' => 'МКР (Биг Бэг)',
                'title_en' => 'Big Bag (FIBC)',
                'title_tm' => 'MKR (Uly Torba)',
                'description_ru' => '<p>4 стропный &ndash; 30 см &nbsp;<br>Ширина &ndash; от 75 см &nbsp;<br>Плотность до 200 гр/м2 &nbsp;<br>УФ &ndash; 1,5% &nbsp;<br>Грузоподъёмность &ndash; от 1000 кг &nbsp;</p>\r\n<p>Верх &ndash; открытый<br>Низ &ndash; люк</p>',
                'description_en' => '<p>4 loops &ndash; 30 cm &nbsp;<br>Width: from 75 cm &nbsp;<br>Density: up to 200 g/m&sup2; &nbsp;<br>UV protection: 1.5% &nbsp;<br>Load capacity: from 1000 kg &nbsp;</p>\r\n<p>Top &ndash; open &nbsp;<br>Bottom &ndash; discharging spout</p>',
                'description_tm' => '<p>4 a&yacute;lawly &ndash; 30 sm &nbsp;<br>Ini: 75 sm-den başla&yacute;ar &nbsp;<br>Dykyzlygy: 200 gr/m&sup2; &ccedil;enli &nbsp;<br>UV goragy: 1,5% &nbsp;<br>&Yacute;&uuml;k g&ouml;terijiligi: 1000 kg-dan başla&yacute;ar &nbsp;</p>\r\n<p>&Yacute;okary &ndash; a&ccedil;yk&nbsp;<br>Aşagy &ndash; agyz&nbsp;</p>',
                'is_active' => 1,
                'img' => 'img/p8.jpg',
                'ordering' => 0,
                'created_at' => '2024-12-27 06:18:18',
                'updated_at' => '2024-12-27 06:18:18',
            ],
            [
                'id' => 9,
                'title_ru' => 'МКР (Биг Бэг)',
                'title_en' => 'Big Bag (FIBC)',
                'title_tm' => 'MKR (Uly Torba)',
                'description_ru' => '<p>4 стропный &ndash; 30 см &nbsp;<br>Ширина &ndash; от 75 см &nbsp;<br>Плотность до 200 гр/м2 &nbsp;<br>УФ &ndash; 1,5% &nbsp;<br>Грузоподъёмность &ndash; от 1000 кг &nbsp;</p>\r\n<p>Верх &ndash; сборка (юбка) &nbsp;<br>Низ &ndash; люк</p>',
                'description_en' => '<p>4 loops &ndash; 30 cm &nbsp;<br>Width: from 75 cm &nbsp;<br>Density: up to 200 g/m&sup2; &nbsp;<br>UV protection: 1.5% &nbsp;<br>Load capacity: from 1000 kg</p>\r\n<p>Top &ndash; skirt &nbsp;<br>Bottom &ndash; discharging spout</p>',
                'description_tm' => '<p>4 a&yacute;lawly &ndash; 30 sm &nbsp;<br>Ini: 75 sm-den başla&yacute;ar &nbsp;<br>Dykyzlygy: 200 gr/m&sup2; &ccedil;enli &nbsp;<br>UV goragy: 1,5% &nbsp;<br>&Yacute;&uuml;k g&ouml;terijiligi: 1000 kg-dan başla&yacute;ar</p>\r\n<p>&Yacute;okary &ndash; &yacute;ygnama (&yacute;&uuml;bka) &nbsp;<br>Aşagy &ndash; boşadyş agzy&nbsp;</p>',
                'is_active' => 1,
                'img' => 'img/p9.jpg',
                'ordering' => 0,
                'created_at' => '2024-12-27 06:22:47',
                'updated_at' => '2024-12-27 06:22:47',
            ],
            [
                'id' => 10,
                'title_ru' => 'МКР (Биг Бэг)',
                'title_en' => 'Big Bag (FIBC)',
                'title_tm' => 'MKR (Uly Torba)',
                'description_ru' => '<p>4 стропный &ndash; 30 см &nbsp;<br>Ширина &ndash; от 75 см &nbsp;<br>Плотность до 200 гр/м2 &nbsp;<br>УФ &ndash; 1,5% &nbsp;<br>Грузоподъёмность &ndash; от 1000 кг &nbsp;</p>\r\n<p>Верх &ndash; люк<br>Низ &ndash; глухой</p>',
                'description_en' => '<p>4 loops &ndash; 30 cm &nbsp;<br>Width: from 75 cm &nbsp;<br>Density: up to 200 g/m&sup2; &nbsp;<br>UV protection: 1.5% &nbsp;<br>Load capacity: from 1000 kg &nbsp;</p>\r\n<p>Top &ndash; filling spout &nbsp;<br>Bottom &ndash; closed</p>',
                'description_tm' => '<p>4 a&yacute;lawly &ndash; 30 sm &nbsp;<br>Ini: 75 sm-den başla&yacute;ar &nbsp;<br>Dykyzlygy: 200 gr/m&sup2; &ccedil;enli &nbsp;<br>UV goragy: 1,5% &nbsp;<br>&Yacute;&uuml;k g&ouml;terijiligi: 1000 kg-dan başla&yacute;ar &nbsp;</p>\r\n<p>&Yacute;okary &ndash; agyz<br>Aşagy &ndash; &yacute;apyk&nbsp;</p>',
                'is_active' => 1,
                'img' => 'img/p10.jpg',
                'ordering' => 0,
                'created_at' => '2024-12-27 06:27:47',
                'updated_at' => '2024-12-27 06:27:47',
            ],
            [
                'id' => 11,
                'title_ru' => 'МКР (Биг Бэг)',
                'title_en' => 'Big Bag (FIBC)',
                'title_tm' => 'MKR (Uly Torba)',
                'description_ru' => '<p>4 стропный &ndash; 30 см &nbsp;<br>Ширина &ndash; от 75 см &nbsp;<br>Плотность до 200 гр/м2 &nbsp;<br>УФ &ndash; 1,5% &nbsp;<br>Грузоподъёмность &ndash; от 1000 кг</p>\r\n<p>Верх &ndash; сборка (юбка) &nbsp;<br>Низ &ndash; глухой</p>',
                'description_en' => '<p>4 loops &ndash; 30 cm &nbsp;<br>Width: from 75 cm &nbsp;<br>Density: up to 200 g/m&sup2; &nbsp;<br>UV protection: 1.5% &nbsp;<br>Load capacity: from 1000 kg</p>\r\n<p>Top &ndash; skirt &nbsp;<br>Bottom &ndash; closed</p>',
                'description_tm' => '<p>4 a&yacute;lawly &ndash; 30 sm &nbsp;<br>Ini: 75 sm-den başla&yacute;ar &nbsp;<br>Dykyzlygy: 200 gr/m&sup2; &ccedil;enli &nbsp;<br>UV goragy: 1,5% &nbsp;<br>&Yacute;&uuml;k g&ouml;terijiligi: 1000 kg-dan başla&yacute;ar</p>\r\n<p>&Yacute;okary &ndash; &yacute;ygnama (&yacute;&uuml;bka) &nbsp;<br>Aşagy &ndash; &yacute;apyka&yacute;ar</p>',
                'is_active' => 1,
                'img' => 'img/p11.jpg',
                'ordering' => 0,
                'created_at' => '2024-12-27 06:31:05',
                'updated_at' => '2024-12-27 06:31:05',
            ],
        ]);
    }
}
